addons:
  postgresql: '9.4'
before_script:
  - cp config/database.yml.sample config/database.yml
cache: bundler
language: ruby
rvm:
- 2.4.1
services:
  - postgresql
script:
  - bundle exec rails db:setup
  - bundle exec rspec
sudo: required
